object fnavegador: Tfnavegador
  Left = 0
  Top = 0
  BorderIcons = [biSystemMenu]
  BorderStyle = bsSizeToolWin
  Caption = 'Navegador'
  ClientHeight = 373
  ClientWidth = 234
  Color = clBtnFace
  DragKind = dkDock
  DragMode = dmAutomatic
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'Tahoma'
  Font.Style = []
  OldCreateOrder = False
  Position = poDefault
  PrintScale = poNone
  OnCreate = FormCreate
  PixelsPerInch = 96
  TextHeight = 13
  object TreeView1: TTreeView
    Left = 0
    Top = 0
    Width = 234
    Height = 373
    Align = alClient
    Indent = 19
    TabOrder = 0
    OnDblClick = TreeView1DblClick
    ExplicitWidth = 244
    ExplicitHeight = 379
  end
end
